$foreground = rgb(CBF0F3)
$background = rgb(04070D)
$cursor = rgb(909BAB)
$color0 = rgb(3D3E43)
$color1 = rgb(509FA5)
$color2 = rgb(998D9C)
$color3 = rgb(458191)
$color4 = rgb(8F728F)
$color5 = rgb(6A6374)
$color6 = rgb(4B6778)
$color7 = rgb(ADE1E5)
$color8 = rgb(799EA0)
$color9 = rgb(6BD4DC)
$color10 = rgb(CCBCD0)
$color11 = rgb(3290A9)
$color12 = rgb(9E6D9C)
$color13 = rgb(7B7087)
$color14 = rgb(50778C)
$color15 = rgb(ADE1E5)


$wallpaper = /home/joyjosr/wallpapers/miku.jpg
